[package]
name = "rust-magicsquare"
version = "0.1.0"
authors = ["st1hy <st1hy@outlook.com>"]

[dependencies]
rand = "*"
chan = "*"
chan-signal = "*"
num_cpus = "*"
chrono = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"